### ISSUE TITLE
Response 403

### ISSUE THREAD

**Issue by research555** [saadmanrafat/twitivity#10]
Hi Saadman,

I've been experiencing an issue trying to register my webhook. The code I have looks something like this:

In the file stream_events.py:

```python
import json

from twitivity import Event
from pprint import pprint
import os

class StreamEvent(Event):

    CALLBACK_URL: str = "https://0bdb70929c67.ngrok.io/twitter/callback"

    def on_data(self, data: json) -> None:
        pprint(data, indent=2)


if __name__ == "__main__":
    stream_event = StreamEvent()
    stream_event.listen()
```

While in file configure.py:

``` python
from twitivity import Activity

if __name__ == "__main__":
    activity = Activity()
    print(activity.register_webhook(callback_url="https://0bdb70929c67.ngrok.io/twitter/callback"))
    print(activity.subscribe())

```
I currently don't have a webserver and instead use the ngrok URL (which I have since changed). I get the error code:
```
{'errors': [{'code': 214, 'message': 'Non-200 response code during CRC GET request (i.e. 404, 500, etc).'}]}
<Response [403]>
```
Which suggests to me that the POST request is going through, but the CRC token GET request is not.  When I go on localhost:4040 on my web browser, I can see GET requests. In the summary section it says 
```Query Params: crc_token: 'String of text' and nonce: 'string of text' ```
Underneath this however, It continually says waiting to receive a response from your server.

Any help would be appreciated. Bear in mind I have never done anything like this before.

EDIT: It might also be important to note that my ngrok inspect window is not showing any POST requests, only GET.
EDIT2: Also, all my environment variables are set correctly, I have set up a dev env on my twitter page and otherwise followed your guide pretty much to a T.

**Comment by saadmanrafat** [comment]
- There are a number of things to consider here. To start with have `./ngrok` listen on port 5000

  ```
   ./ngrok http 5000
  ```
- Your Twitter Application has Read, Write & Direct Messages permissions.
- Since you are running two processes in parallel. First running `stream_events.py`, which is kind of your local server, **and then running** `configure.py`. There could a possibility that one or both of the processes aren't getting the environment variables. So adding the environment variables on both `stream_event.py` && `configure.py` would a good idea.
   ```python
   import os
  from twitivity import Activity 

   os.environ['consumer_key']=API_KEY
   os.environ['consumer_secret']=API_SECRET_KEY
   os.environ['access_token']=ACCESS_TOKEN
   os.environ['access_token_secret']=ACCESS_TOKEN_SECRET 
   os.environ['env_name']=ENV_NAME # this is the dev environment label name you choose.
   ```

**Comment by research555** [comment]
I'm not sure what happened but it worked when I set my port to 5000 and used the command ```ngrok http 5000``` instead  ```ngrok http https://localhost:5000```. I used the HTTPS address in both cases. Not sure exactly why but its up and running now, thank you for the help! 👍 :)
