### ISSUE TITLE
Documentation URL not working

### ISSUE THREAD

**Issue by legrassy** [saadmanrafat/twitivity#20]
Documentation link in ReadMe redirects to a 404 page.

**Comment by saadmanrafat** [comment]
Sorry about the mishap! We updated our documentation. And now resides at [https://repo.twitivity.dev/]( https://repo.twitivity.dev/). The `README.md` section will be updated promptly. Thank You for raising this issue.

**Comment by saadmanrafat** [comment]
`README.md` [updated](https://github.com/twitivity/twitivity/tree/f293e3f753a20ce50b572ac10a5e613b323038ac).
