### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by saadmanrafat** [saadmanrafat/twitivity#3]
**Is your feature request related to a problem? Please describe.**
  Documentations on how to deploy on Platforms like Heroku

**Comment by alxcnwy** [comment]
It's not clear in the docs where to get your callback_url?

**Comment by saadmanrafat** [comment]
Normally you would use Ngrok or a server with a domain if you have one lying around. For development, purposes you could use [Ngrok](https://ngrok.com/). Please do go through the part about [Usage](https://github.com/saadmanrafat/twitivity#usage) on [README.md](https://github.com/saadmanrafat/twitivity/blob/master/README.md).

**Comment by alxcnwy** [comment]
Got it, thanks Saadman.
